// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Abilities → Questions*
 */
export interface AbilitiesDocumentDataQuestionsItem {
  /**
   * Question field in *Abilities → Questions*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: abilities.questions[].question
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  question: prismic.ContentRelationshipField<"questions">;
}

/**
 * Content for Abilities documents
 */
interface AbilitiesDocumentData {
  /**
   * Name field in *Abilities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: abilities.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * description field in *Abilities*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: abilities.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *Abilities*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: abilities.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Questions field in *Abilities*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: abilities.questions[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  questions: prismic.GroupField<Simplify<AbilitiesDocumentDataQuestionsItem>>;
}

/**
 * Abilities document from Prismic
 *
 * - **API ID**: `abilities`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AbilitiesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AbilitiesDocumentData>,
    "abilities",
    Lang
  >;

type BlogpostDocumentDataSlicesSlice = RichTextSlice;

/**
 * Content for BlogPost documents
 */
interface BlogpostDocumentData {
  /**
   * Title field in *BlogPost*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * date field in *BlogPost*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Image field in *BlogPost*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *BlogPost*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogpostDocumentDataSlicesSlice> /**
   * Meta Description field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogpost.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *BlogPost*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogpost.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * BlogPost document from Prismic
 *
 * - **API ID**: `blogpost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogpostDocumentData>,
    "blogpost",
    Lang
  >;

/**
 * Item in *Champion → Abilities*
 */
export interface ChampionDocumentDataAbilitiesItem {
  /**
   * Spell field in *Champion → Abilities*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: champion.abilities[].spell
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  spell: prismic.ContentRelationshipField<"abilities">;
}

type ChampionDocumentDataSlicesSlice = never;

/**
 * Content for Champion documents
 */
interface ChampionDocumentData {
  /**
   * Name field in *Champion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: champion.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *Champion*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: champion.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Champion*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: champion.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * SplashArt field in *Champion*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: champion.splashart
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  splashart: prismic.ImageField<never>;

  /**
   * release field in *Champion*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: champion.release
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  release: prismic.BooleanField;

  /**
   * Abilities field in *Champion*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: champion.abilities[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  abilities: prismic.GroupField<Simplify<ChampionDocumentDataAbilitiesItem>>;

  /**
   * Slice Zone field in *Champion*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: champion.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ChampionDocumentDataSlicesSlice> /**
   * Meta Description field in *Champion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: champion.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Champion*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: champion.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Champion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: champion.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Champion document from Prismic
 *
 * - **API ID**: `champion`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ChampionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ChampionDocumentData>,
    "champion",
    Lang
  >;

type ChampionsDocumentDataSlicesSlice = never;

/**
 * Content for ChampionsList documents
 */
interface ChampionsDocumentData {
  /**
   * Slice Zone field in *ChampionsList*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: champions.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ChampionsDocumentDataSlicesSlice> /**
   * Meta Description field in *ChampionsList*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: champions.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *ChampionsList*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: champions.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *ChampionsList*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: champions.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * ChampionsList document from Prismic
 *
 * - **API ID**: `champions`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ChampionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ChampionsDocumentData>,
    "champions",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | BlogShowcaseSlice
  | VideoShowcaseSlice
  | GamingSiteFactsSlice
  | HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice = RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Patch documents
 */
interface PatchDocumentData {
  /**
   * Version field in *Patch*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: patch.version
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  version: prismic.KeyTextField;
}

/**
 * Patch document from Prismic
 *
 * - **API ID**: `patch`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PatchDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PatchDocumentData>, "patch", Lang>;

/**
 * Content for Position documents
 */
interface PositionDocumentData {
  /**
   * Name field in *Position*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: position.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Icon field in *Position*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: position.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Position document from Prismic
 *
 * - **API ID**: `position`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PositionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PositionDocumentData>,
    "position",
    Lang
  >;

/**
 * Item in *Questions → Options*
 */
export interface QuestionsDocumentDataOptionsItem {
  /**
   * Label field in *Questions → Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.options[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * isCorrect field in *Questions → Options*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: questions.options[].iscorrect
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  iscorrect: prismic.BooleanField;
}

/**
 * Content for Questions documents
 */
interface QuestionsDocumentData {
  /**
   * Question field in *Questions*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.question
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  question: prismic.RichTextField;

  /**
   * Options field in *Questions*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.options[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  options: prismic.GroupField<Simplify<QuestionsDocumentDataOptionsItem>>;
}

/**
 * Questions document from Prismic
 *
 * - **API ID**: `questions`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type QuestionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<QuestionsDocumentData>,
    "questions",
    Lang
  >;

/**
 * Content for Range Type documents
 */
interface RangeTypeDocumentData {
  /**
   * Name field in *Range Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: range_type.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Icon field in *Range Type*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: range_type.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Range Type document from Prismic
 *
 * - **API ID**: `range_type`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RangeTypeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<RangeTypeDocumentData>,
    "range_type",
    Lang
  >;

/**
 * Content for Role documents
 */
interface RoleDocumentData {
  /**
   * Name field in *Role*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: role.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Icon field in *Role*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: role.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Role document from Prismic
 *
 * - **API ID**: `role`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RoleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<RoleDocumentData>, "role", Lang>;

/**
 * Item in *settings → NavItems*
 */
export interface SettingsDocumentDataNavitemsItem {
  /**
   * Label field in *settings → NavItems*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navitems[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *settings → NavItems*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navitems[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *settings → Navigation Signed Out Actions*
 */
export interface SettingsDocumentDataNavigationSignedOutActionsItem {
  /**
   * Label field in *settings → Navigation Signed Out Actions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_signed_out_actions[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * CTA field in *settings → Navigation Signed Out Actions*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.navigation_signed_out_actions[].cta
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  cta: prismic.BooleanField;

  /**
   * Link field in *settings → Navigation Signed Out Actions*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_signed_out_actions[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * clerk field in *settings → Navigation Signed Out Actions*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.navigation_signed_out_actions[].clerk
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  clerk: prismic.BooleanField;
}

/**
 * Item in *settings → Navigation Signed In Actions*
 */
export interface SettingsDocumentDataNavigationSignedInActionsItem {
  /**
   * Label field in *settings → Navigation Signed In Actions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_signed_in_actions[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *settings → Navigation Signed In Actions*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_signed_in_actions[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * CTA field in *settings → Navigation Signed In Actions*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.navigation_signed_in_actions[].cta
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  cta: prismic.BooleanField;

  /**
   * clerk field in *settings → Navigation Signed In Actions*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.navigation_signed_in_actions[].clerk
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  clerk: prismic.BooleanField;
}

/**
 * Item in *settings → Social Media*
 */
export interface SettingsDocumentDataSocialMediaItem {
  /**
   * Link field in *settings → Social Media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_media[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Icon field in *settings → Social Media*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_media[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<"Facebook" | "Instagram" | "Twitter" | "Youtube">;
}

/**
 * Item in *settings → FooterItems*
 */
export interface SettingsDocumentDataFooteritemsItem {
  /**
   * Label field in *settings → FooterItems*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footeritems[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *settings → FooterItems*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footeritems[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for settings documents
 */
interface SettingsDocumentData {
  /**
   * Logo field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * NavItems field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navitems[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navitems: prismic.GroupField<Simplify<SettingsDocumentDataNavitemsItem>>;

  /**
   * Navigation Signed Out Actions field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_signed_out_actions[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation_signed_out_actions: prismic.GroupField<
    Simplify<SettingsDocumentDataNavigationSignedOutActionsItem>
  >;

  /**
   * Navigation Signed In Actions field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_signed_in_actions[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation_signed_in_actions: prismic.GroupField<
    Simplify<SettingsDocumentDataNavigationSignedInActionsItem>
  >;

  /**
   * Social Media field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_media[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media: prismic.GroupField<
    Simplify<SettingsDocumentDataSocialMediaItem>
  >;

  /**
   * FooterItems field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footeritems[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footeritems: prismic.GroupField<
    Simplify<SettingsDocumentDataFooteritemsItem>
  >;

  /**
   * Copyright field in *settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copyright: prismic.RichTextField;

  /**
   * Newsletter  field in *settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsletter
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  newsletter: prismic.RichTextField;

  /**
   * Footer Letter field in *settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_letter
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_letter: prismic.RichTextField;

  /**
   * footer Background field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_background
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footer_background: prismic.ImageField<never>;
}

/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | AbilitiesDocument
  | BlogpostDocument
  | ChampionDocument
  | ChampionsDocument
  | HomeDocument
  | PageDocument
  | PatchDocument
  | PositionDocument
  | QuestionsDocument
  | RangeTypeDocument
  | RoleDocument
  | SettingsDocument;

/**
 * Primary content in *BlogShowcase → Primary*
 */
export interface BlogShowcaseSliceDefaultPrimary {
  /**
   * Title field in *BlogShowcase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_showcase.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *BlogShowcase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_showcase.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Primary content in *BlogShowcase → Items*
 */
export interface BlogShowcaseSliceDefaultItem {
  /**
   * Featured Blogs field in *BlogShowcase → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_showcase.items[].featured_blogs
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  featured_blogs: prismic.ContentRelationshipField;
}

/**
 * Default variation for BlogShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogShowcaseSliceDefaultPrimary>,
  Simplify<BlogShowcaseSliceDefaultItem>
>;

/**
 * Slice variation for *BlogShowcase*
 */
type BlogShowcaseSliceVariation = BlogShowcaseSliceDefault;

/**
 * BlogShowcase Shared Slice
 *
 * - **API ID**: `blog_showcase`
 * - **Description**: BlogShowcase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogShowcaseSlice = prismic.SharedSlice<
  "blog_showcase",
  BlogShowcaseSliceVariation
>;

/**
 * Primary content in *GamingSiteFacts → Primary*
 */
export interface GamingSiteFactsSliceDefaultPrimary {
  /**
   * Jumbotron field in *GamingSiteFacts → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gaming_site_facts.primary.jumbotron
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  jumbotron: prismic.ImageField<never>;

  /**
   * Subtitle field in *GamingSiteFacts → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gaming_site_facts.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Title field in *GamingSiteFacts → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: gaming_site_facts.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *GamingSiteFacts → Items*
 */
export interface GamingSiteFactsSliceDefaultItem {
  /**
   * Icon field in *GamingSiteFacts → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: gaming_site_facts.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<"Game" | "Wings" | "Headphones">;

  /**
   * Fact field in *GamingSiteFacts → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gaming_site_facts.items[].fact
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fact: prismic.RichTextField;

  /**
   * description field in *GamingSiteFacts → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gaming_site_facts.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for GamingSiteFacts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GamingSiteFactsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GamingSiteFactsSliceDefaultPrimary>,
  Simplify<GamingSiteFactsSliceDefaultItem>
>;

/**
 * Slice variation for *GamingSiteFacts*
 */
type GamingSiteFactsSliceVariation = GamingSiteFactsSliceDefault;

/**
 * GamingSiteFacts Shared Slice
 *
 * - **API ID**: `gaming_site_facts`
 * - **Description**: GamingSiteFacts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GamingSiteFactsSlice = prismic.SharedSlice<
  "gaming_site_facts",
  GamingSiteFactsSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * CTA Label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *VideoShowcase → Primary*
 */
export interface VideoShowcaseSliceDefaultPrimary {
  /**
   * thumbnailOverride field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.primary.thumbnailoverride
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnailoverride: prismic.ImageField<never>;

  /**
   * Title field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * YoutubeID field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.primary.youtubeid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  youtubeid: prismic.KeyTextField;
}

/**
 * Default variation for VideoShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoShowcaseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoShowcase*
 */
type VideoShowcaseSliceVariation = VideoShowcaseSliceDefault;

/**
 * VideoShowcase Shared Slice
 *
 * - **API ID**: `video_showcase`
 * - **Description**: VideoShowcase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoShowcaseSlice = prismic.SharedSlice<
  "video_showcase",
  VideoShowcaseSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AbilitiesDocument,
      AbilitiesDocumentData,
      AbilitiesDocumentDataQuestionsItem,
      BlogpostDocument,
      BlogpostDocumentData,
      BlogpostDocumentDataSlicesSlice,
      ChampionDocument,
      ChampionDocumentData,
      ChampionDocumentDataAbilitiesItem,
      ChampionDocumentDataSlicesSlice,
      ChampionsDocument,
      ChampionsDocumentData,
      ChampionsDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PatchDocument,
      PatchDocumentData,
      PositionDocument,
      PositionDocumentData,
      QuestionsDocument,
      QuestionsDocumentData,
      QuestionsDocumentDataOptionsItem,
      RangeTypeDocument,
      RangeTypeDocumentData,
      RoleDocument,
      RoleDocumentData,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavitemsItem,
      SettingsDocumentDataNavigationSignedOutActionsItem,
      SettingsDocumentDataNavigationSignedInActionsItem,
      SettingsDocumentDataSocialMediaItem,
      SettingsDocumentDataFooteritemsItem,
      AllDocumentTypes,
      BlogShowcaseSlice,
      BlogShowcaseSliceDefaultPrimary,
      BlogShowcaseSliceDefaultItem,
      BlogShowcaseSliceVariation,
      BlogShowcaseSliceDefault,
      GamingSiteFactsSlice,
      GamingSiteFactsSliceDefaultPrimary,
      GamingSiteFactsSliceDefaultItem,
      GamingSiteFactsSliceVariation,
      GamingSiteFactsSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      VideoShowcaseSlice,
      VideoShowcaseSliceDefaultPrimary,
      VideoShowcaseSliceVariation,
      VideoShowcaseSliceDefault,
    };
  }
}
