// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  gaming_site_facts: dynamic(() => import("./GamingSiteFacts")),
  hero: dynamic(() => import("./Hero")),
  rich_text: dynamic(() => import("./RichText")),
  video_showcase: dynamic(() => import("./VideoShowcase")),
};
